# Generated by Django 5.0.3 on 2024-04-13 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
