# Generated by Django 5.0.3 on 2024-05-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_pub_data_post_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='age',
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
