# Generated by Django 5.0.3 on 2024-05-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tag_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='comment', to='main.tag'),
        ),
    ]
